on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Yarn install
      uses: actions/setup-node@v6
      with:
        node-version: 20.x
    - run: yarn install --cwd example --frozen-lockfile
    - run: yarn install --frozen-lockfile
    - run: yarn typescript
    - run: yarn lint
